ConfigACC          	= {}

ConfigACC.AntiVPN = false
ConfigACC.AntiVPNDiscordLogs = true

ConfigACC.GlobalCheat = true

ConfigACC.AntiBlips = true
ConfigACC.AntiSpectate = true
ConfigACC.AntiESX = true

ConfigACC.AntiResourceStart = true
ConfigACC.AntiResourceStop = true
ConfigACC.AntiResourceRestart = true
ConfigACC.ResourceCount = true
ConfigACC.AntiInjection = true

ConfigACC.WeaponProtection = true
ConfigACC.TriggersProtection = true
ConfigACC.WordsProtection = true
ConfigACC.GiveWeaponsProtection = true
ConfigACC.ExplosionProtection = true
ConfigACC.AntiClearPedTask = true

ConfigACC.BanBlacklistedWeapon = true

ConfigACC.BlacklistedCommands = {
    'pk',
    'haha',
    'lol',
    'xddd',
    'chocolate',
	'panickey',
	'jolmany',
	'killmenu'
}

ConfigACC.BlockedExplosions = {
	0,
	1,
	2,
	3,
	4,
	5,
	25,
	32,
	33,
	35,
	36,
	37,
	38
}

ConfigACC.BlacklistedWords = {
	'Desudo',
	'Brutan',
	'EulenCheats',
	"discord.gg/",
	"lynxmenu",
	"HamHaxia",
	"Ham Mafia",
	"www.renalua.com",
	"Fallen#0811",
	"Rena 8",
	"HamHaxia", 
	"Ham Mafia", 
	"Xanax#0134", 
	">:D Player Crash", 
	"discord.gg", 
	"34ByTe Community", 
	"lynxmenu.com", 
	"Anti-LRAC",
	"Baran#8992",
	"iLostName#7138",
	"85.190.90.118",
	"Melon#1379",
	"hammafia.com",
	"AlphaV ~ 5391",
	"vjuton.pl",
	"Soviet Bear",
	"XARIES",
	"xaries",
	"dc.xaries.pl",
	"aries",
	"aries.pl",
	"youtube.com/c/Aries98/",
	"Aries98",
	"yo many",
	"dezet",
	"333",
	"333GANG",
	
}

-- Blacklisted weapons that players can never have
ConfigACC.BlacklistedWeapons = {
    'WEAPON_GRENADELAUNCHER',
	'WEAPON_RPG',
	'WEAPON_STINGER',
	'WEAPON_MINIGUN',
	'WEAPON_GRENADE',
	'WEAPON_STICKYBOMB',
	'WEAPON_RAILGUN',
	'WEAPON_COMPACTLAUNCHER',
	'WEAPON_PIPEBOMB',
	'WEAPON_PROXMINE',
	'WEAPON_GRENADELAUNCHER_SMOKE',
	'WEAPON_FIREWORK',
	'WEAPON_HOMINGLAUNCHER',
	'WEAPON_RAYPISTOL',
	'WEAPON_RAYCARBINE',
	'WEAPON_RAYMINIGUN',
	'WEAPON_DIGISCANNER',
}

-- Blacklisted vehicles
ConfigACC.BlacklistedModels = { -- only peds/vehicles
	--VEHICLES
	"skylift",
	"valkyrie2",
	"airbus",
	"hunter",
	"bus",
	"armytanker",
	"armytrailer",
	"armytrailer2",
	"baletrailer",
	"boattrailer",
	"cablecar",
	"docktrailer",
	"freighttrailer",
	"graintrailer",
	"proptrailer",
	"raketrailer",
	"tr2",
	"tug",
	"tr3",
	"tr4",
	"trflat",
	"tvtrailer",
	"tanker",
	"tanker2",
	"trailerlarge",
	"trailerlogs",
	"trailersmall",
	"trailers",
	"trailers2",
	"trailers3",
	"trailers4",
	'RHINO',
	'AKULA',
	'SAVAGE',
	'HUNTER',
	'BUZZARD',
	'BUZZARD2',
	'ANNIHILATOR',
	'VALKYRIE',
	'HYDRA',
	'APC',
	'Trailersmall2',
	'Lazer',
	'oppressor',
	'mogul',
	'barrage',
	'Khanjali',
	'volatol',
	'chernobog',
	'avenger',
	'stromberg',
	'nightshark',
	'besra',
	'babushka ',
	'starling',
	'insurgent',
	'cargobob',
	'cargobob2',
	'cargobob3',
	'cargobob4',
	'caracara',
	'deluxo',
	'menacer',
    'scramjet',
    'oppressor2',
    'revolter',
    'viseris',
    'savestra',
    'thruster',
    'ardent',
    'dune3',
    'tampa3',
    'halftrack',
    'nokota',
    'strikeforce',
    'bombushka',
    'molotok',
    'pyro',
    'ruiner2',
    'limo2',
    'technical',
    'technical2',
    'technical3',
    'jb700w',
    'blazer5',
    'insurgent3',
	'boxville5',
	'bruiser',
    'bruiser2',
    'bruiser3',
    'brutus',
    'brutus2',
    'brutus3',
    'cerberus',
    'cerberus2',
    'cerberus3',
    'dominator4',
    'dominator5',
    'dominator6',
    'impaler2',
    'impaler3',
    'impaler4',
    'imperator',
    'imperator2',
    'imperator3',
    'issi4',
    'issi5',
    'issi6',
    'monster3',
    'monster4',
    'monster5',
    'scarab',
    'scarab2',
    'scarab3',
    'slamvan4',
    'slamvan5',
    'slamvan6',
    'zr380',
    'zr3802',
    'zr3803',
	'alphaz1',
	'avenger2',
	'blimp',
	'blimp2',
	'blimp3',
	'cargoplane',
	'cuban800',
	'dodo',
	'duster',
	'howard',
	'jet',
	'luxor',
	'luxor2',
	'mammatus',
	'microlight',
	'miljet',
	'nimbus',
	'rogue',
	'seabreeze',
	'shamal',
	'stunt',
	'titan',
	'tula',
	'velum',
	'velum2',
	'vestra',

	-- PEDS
	"s_m_y_swat_01",
	"a_m_o_acult_01",
	"ig_wade",
	"s_m_y_hwaycop_01",
	"A_M_Y_ACult_01",
	's_m_m_movalien_01',
	's_m_m_movallien_01',
	'u_m_y_babyd',
	'CS_Orleans',
	'A_M_Y_ACult_01',
	'S_M_M_MovSpace_01',
	'U_M_Y_Zombie_01',
	's_m_y_blackops_01',
	'a_f_y_topless_01',
	'a_c_boar',
	'a_c_cat_01',
	'a_c_chickenhawk',
	'a_c_chimp',
	's_f_y_hooker_03',
	'a_c_chop',
	'a_c_cormorant',
	'a_c_cow',
	'a_c_coyote',
	'a_c_crow',
	'a_c_dolphin',
	'a_c_fish',
	's_f_y_hooker_01',
	'a_c_hen',
	'a_c_humpback',
	'a_c_husky',
	'a_c_killerwhale',
	'a_c_mtlion',
	'a_c_pigeon',
	'a_c_poodle',
	'a_c_pug',
	'a_c_rabbit_01',
	'a_c_rat',
	'a_c_retriever',
	'a_c_rhesus',
	'a_c_rottweiler',
	'a_c_sharkhammer',
	'a_c_sharktiger',
	'a_c_shepherd',
	'a_c_stingray',
	'a_c_westy',
	'CS_Orleans',
}

ConfigACC.WhitelistedProps = {
	"prop_ballistic_shield",
}

ConfigACC.BlacklistedEvents = {	
	--drogue
	"esx_drugs:startHarvestWeed",
	"esx_drugs:startHarvestCoke",
	"esx_drugs:startHarvestMeth",
	"esx_drugs:startHarvestOpium",
	"esx_drugs:stopHarvestWeed",
	"esx_drugs:stopHarvestCoke",
	"esx_drugs:stopHarvestMeth",
	"esx_drugs:stopHarvestOpium",
	"esx_drugs:startTransformWeed",
	"esx_drugs:startTransformCoke",
	"esx_drugs:startTransformMeth",
	"esx_drugs:startTransformOpium",
	"esx_drugs:stopTransformWeed",
	"esx_drugs:stopTransformCoke",
	"esx_drugs:stopTransformMeth",
	"esx_drugs:stopTransformOpium",
	"esx_drugs:startSellWeed",
	"esx_drugs:startSellCoke",
	"esx_drugs:startSellMeth",
	"esx_drugs:startSellOpium",
	"esx_drugs:stopSellWeed",
	"esx_drugs:stopSellCoke",
	"esx_drugs:stopSellMeth",
	"esx_drugs:stopSellOpium",

	--NTH_banque
	"RetiréArgent",
	"PoserArgent",
	"solde:argent",

	--NTH_core
	"nth_store:Buy",
	"nth_store:GetConfig",

	--NTH_f5
	"BUG_REPORT",

	--Nth_admin
	"getSteamID",
	"returnSteamID",
	"admin:Freeze",

	--Interact-sound
	"InteractSound_SV:PlayOnOne",
	"InteractSound_SV:PlayOnSource",
	"InteractSound_SV:PlayOnAll",
	"InteractSound_SV:PlayWithinDistance",
	"InteractSound_CL:PlayOnOne",
	"InteractSound_CL:PlayOnAll",
	"InteractSound_CL:PlayWithinDistanceOS",
	"InteractSound_CL:PlayWithinDistance",

	--esx_policejob
	"esx_policejob:giveWeapon",
	"esx_policejob:pedExists",
	"esx_policejob:updateBlip",
	"esx_policejob:handcuff",
	"esx_policejob:drag",
	"esx_policejob:putInVehicle",
	"esx_policejob:OutVehicle",
	"renfort",
	"esx_policejob:getOtherPlayerData",
	"esx_policejob:confiscatePlayerItem",
	"esx_policejob:getFineList",
	"esx_policejob:getVehicleInfos",
	"esx_policejob:message",
	"esx_policejob:getArmoryWeapons",
	"esx_policejob:removeArmoryWeapon",
	"esx_policejob:addArmoryWeapon",
	"esx_policejob:buyWeapon",
	"esx_policejob:getStockItems",
	"esx_policejob:getStockItem",
	"esx_policejob:getPlayerInventory",
	"esx_policejob:forceBlip",
	"esx_policejob:hasExitedMarker",
	"esx_policejob:hasEnteredMarker",
	"esx_policejob:hasEnteredEntityZone",
	"esx_policejob:hasExitedEntityZone",
	"esx_policejob:unrestrain",
	"esx_policejob:spawned",
	"esx_policejob:spawned",
	"esx_policejob:unrestrain",
	"esx_policejob:storeNearbyVehicle",
	"esx_policejob:buyJobVehicle",
	"renfort:setBlip",
	"esx_policejob:updateBlip"
}